# Exomiser Configuration File - MVA Hackathon 2026
# Data Directory (Centralized on SSD)
exomiser.data-directory=/mnt/e/exomiser_data

# Phenotype Data
exomiser.phenotype.data-version=2406

# HG38 Assembly Data
exomiser.hg38.data-version=2406

# Caching (Optimizado para WSL2)
spring.cache.type=none
logging.level.com.zaxxer.hikari=ERROR
